### ISSUE TITLE
Strange import behavior with pdfjs v4

### ISSUE THREAD

**Issue by dwickern** [embroider-build/ember-auto-import#614]
Repro here: https://github.com/dwickern/ember-pdfjs-reproduction

After upgrading pdfjs from v3 to v4, its default export is an unresolved promise:

<img width="629" alt="Screenshot 2024-03-13 at 3 07 21 PM" src="https://github.com/embroider-build/ember-auto-import/assets/752885/b0dbf869-e0d0-4d93-be6f-8794e8aeed19">

To get it working, you actually have to `await` the imported module:
https://github.com/dwickern/ember-pdfjs-reproduction/commit/f8aa137a5c9e858fa6dd293cfc00087c2f03dacc

**Comment by dwickern** [comment]
There's a similar issue building with embroider, where the application route class is an unresolved promise:
<img width="552" alt="Screenshot 2024-03-13 at 3 32 56 PM" src="https://github.com/embroider-build/ember-auto-import/assets/752885/c75b7c21-ac7e-41e9-acab-f622b0a85cb7">

Which manifests as an error:
```
Uncaught Error: Assertion Failed: Failed to create an instance of 'route:application'. Most likely an improperly defined class or an invalid module export.
    at assert (index.js:118:1)
    at InternalFactoryManager.create (index.js:372:1)
    at Proxy.create (index.js:204:1)
    at instantiateFactory (index.js:276:1)
    at lookup (index.js:223:1)
    at Container.lookup (index.js:121:1)
    at ApplicationInstance.lookup (container_proxy.js:19:1)
    at PrivateRouter.getRoute (router.js:183:1)
    at UnresolvedRouteInfoByParam.fetchRoute (router_js.js:714:1)
    at get route (router_js.js:648:1)
```

Reproduction is on the `embroider` branch: https://github.com/dwickern/ember-pdfjs-reproduction/tree/embroider

**Comment by ef4** [comment]
The commentary in https://github.com/embroider-build/embroider/issues/1948#issuecomment-2135678186 also applies here. 

And the same workaround should apply. The only difference is that for ember-auto-import you must make sure you opted in to [dynamic import support](https://github.com/embroider-build/ember-auto-import?tab=readme-ov-file#dynamic-import).
